name: Arkleg Frontend 

on: 
  push:
    branches: [ main ]
    
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Code
       uses: actions/checkout@v2
       with: 
        ref: main
        
     - name: Deploy with SSH
       uses: fifsky/ssh-action@master
       with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SECRET_KEY }}
          pass: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          command: |
             cd ${{ secrets.REMOTE_PATH }} || exit 1
             git fetch --all
             git reset --hard origin/main
             git clean -df
             npm install --legacy-peer-deps
             npm run build
             sudo systemctl restart nginx
